### ISSUE TITLE
Support a JWT option to set the "kid" (key ID) header field

### ISSUE THREAD

**Issue by cwirving** [cross-org/jwt#4]
I am using this library to test OIDC client code and one of the scenarios I encountered is the case where I need to build a token that refers to a specific key in a JWKS key set.

As an enhancement, I would like to be able to set the "kid" header field to a value of my choice. I think that this is as simple as adding a new field to JWTOptions and making sure to copy its value into the header, if the option is present.

I am happy to contribute a PR to do this, but I want to make sure that you're OK with this first.

**Comment by Pinta365** [comment]
Hello @cwirving. Sounds like a solid improvement. Very happy to take a PR for that :)

**Comment by cwirving** [comment]
Cool. It'll probably be a few days before I can find the time to work on it but, in the meantime: do you have a naming preference? I.e., should the option be named after the corresponding header field name (`kid`) or a more spelled-out name (`keyId`)? From the rest of the naming in the library, I would assume that `keyId` is more consistent.

**Comment by Pinta365** [comment]
Hey, no rush, its summer :)

Since it is a commonly used header we should name it `kid` in my opinion. Like I did with `alg` and `typ` [here](https://github.com/cross-org/jwt/blob/2e430eb3561da10181487941eac12ddaf4274f02/src/sign.ts#L123)

**Comment by Pinta365** [comment]
Oh wait, I just read your question again... :) For the option you can definitely spell it out like `keyId`, thats nice :)

**Comment by cwirving** [comment]
As I started work on the PR, I realized that I could make it a bit more general and useful for people that need to work with the JWT header -- either to inject claims (like my `kid` injection use case) or to read them (such as somebody validating tokens from an OIDC issuer that uses JWK sets, where reading the `kid` header claim is needed to look up the correct key to validate the token).

I hope that this is OK.

**Comment by Pinta365** [comment]
Looks sweet, I approved the PR after it passed the checks but it seems the checks failed after merge, not sure why but i'm sure its fine. I'm currently on vacation and limited access to stuff, I can dig a bit deeper when I get some time.

I'll keep this issue open until someone (feel free if you like :) ) gets time to commit a short section in the `README` about the functionality and a version bump in `deno.jsonc` to trigger a new version to be published.

EDIT: Oh, right. this repo publish on releases, I'll do that once we're done here. :) We still need a readme update and version bump.

**Comment by Pinta365** [comment]
Looking at the code some more I think we also should add a index signature to the JOSEHeader to allow for custom claims without type errors. Like I did with the [JWTPayload](https://github.com/cross-org/jwt/blob/51da4acf5f814dd39bf5cbe83100f15818ac5da1/src/standardclaims.ts#L85). Or did I missunderstand how you intended this functionality to be used? Or got a better idea?

Something like...

```typescript
export interface JOSEHeader {
    //The current properties... alg, typ, kid.. 
    
    // Allow for additional custom claims
    [key: string]: any; 
}
```

**Comment by cwirving** [comment]
I'm happy to do that.

**Comment by Pinta365** [comment]
Nice, I will crack open a new beer and keep having some more summer vacation for now then :) Have a good day/evening :)

**Comment by cwirving** [comment]
I submitted a PR with the updates to the header interface and additions to the README that hopefully cover the new functionality without going into too much detail.

I did not do the version bump in the deno.json file for now, though. I figure that it makes more sense to land all the changes and only bump the version when everybody is happy and feels that documentation is sufficient, etc.

**Comment by Pinta365** [comment]
Hey, I published a new [version ](https://github.com/cross-org/jwt/releases/tag/0.5.0)with your Header work.

Have a good day/evening :) Hopefully more colab to be had in the future. Check out our [org ](https://github.com/cross-org)for more interesting packages.
